export { ProfilePage } from "./Profile";
export { SignupPage } from "./Signup";
export { SignupThankYouPage } from "./SignupThankYou";
export { LoginPage } from "./Login";
export { ForgotPasswordPage } from "./ForgotPassword";
export { ResetPasswordPage } from "./ResetPassword";
export { ChangePasswordPage } from "./ChangePassword";
export { UserManagementPage } from "./UserManagement";
export { SupportedLocalesPage } from "./Localization";
